data = "BELFOX-EURONEXT BRUSSELS EXCH (XBRU):45:
CHICAGO BOARD OF TRADE (CBT):01:01
CHICAGO MERCANTILE EXCH (CME):02:02
COFFEE,SUGAR,COCOA EXCH (CSC):06:09
COMMODITY EXCHANGE INC (COMEX):04:08
EUREX (EUREX):27:10
EUREX IND EQUITY FUTURES:27E:
FINANCIELE TERMIJNMARKT AMSTR (AEX):28:28
HONG KONG FUTURES EXCH (HKFE):33:27
ICE CLEAR EUROPE:7K:7K
ICE FUTURES CLEARING (BOTCC):03B:
ICE FUTURES EUROPE (IFEU):19:16
INT'L MONETARY MARKET (IMM):16:03
KANSAS CITY EXCHANGE (KCBOT):08:12
KOREAN FUTURES EXCHANGE (KRX):69:
LDN INTL FUT/OPT EXCH (LIFFE):14:22
LIFFE (LIFFE):05:11
MARCHE A TERME INTL DE FRANCE (MATIF):25:17
MEFF RENTA VARIABLE (MEFF-RV):68:
MERCHANTS EXCHANGE (MER):03A:
MID AMERICAN EXCHANGE (MIDAM):03:
MINNEAPOLIS GRAIN EXCH (MGE):09:05
MONEP (MNP):30:47
MONTREAL FUTURES EXCH (MFE):10:29
NEW YORK COTTON EXCH (NYCE):13:07
NEW YORK MERC EXCH (NYMEX):07:06
NEW YORK PORTFOLIO CLEARING:8W:8W
NEW ZEALAND FUTURES EXCH (NZF):34:46
NY FUTURES EXCHANGE (NYFE):15:
OSAKA SECURITIES EXCHANGE (OSE):22:31
PHILADELPHIA BOARD OF TRADE:9B:
SINGAPORE MONETARY EXCH(SIMEX):17:13
SPANISH MEFF RV EXCHANGE (MEFF):32A1:
SYDNEY FUTURES EXCHANGE (SFE):18:15
TAIWAN FUTURES EXCH (TAIFEX):81:
TOKYO COMMODITIES EXCH (TOCOM):55:55
TOKYO GRAIN EXCHANGE (TGE):20T:
TOKYO GRAIN EXCHANGE (TGE):56:
TOKYO INTL FUT EXCH (TFX):23:
TOKYO STOCK EXCHANGE (TSE):24:25
TORONTO FUTURES EXCHANGE (TFE):29:
WINNIPEG GRAIN EXCHANGE (WGE):11:20
"

task :seed_abn_exchanges => :environment do
  system = System.find_by_code('AACC')
  lines = data.split("\n")
  lines.each do |line|
    abn_name, abn_alias  = line.split(':')
    dealing_venue_alias = DealingVenueAlias.find_by_system_id_and_code(system.id, abn_alias)
    print abn_alias
    if dealing_venue_alias
      puts ' GOT'
    else
      puts " NOT #{abn_name}"
    end
  end
end