default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25
  port: 5432

development:
  <<: *default
  host: localhost
  database: alice_development
  username: alice
  password: alice

test:
  <<: *default
  host: localhost
  database: alice_test
  username: alice
  password: alice

integration:
  <<: *default
  host: localhost
  database: alice_integration
  username: alice
  password: <%= begin IO.read("#{ENV['HOME']}/.alice_db_pwd").chomp rescue "" end %>

staging:
  <<: *default
  host: localhost
  database: alice_staging
  username: alice
  password: <%= begin IO.read("#{ENV['HOME']}/.alice_db_pwd").chomp rescue "" end %>

production:
  <<: *default
  host: localhost
  database: alice_production
  username: alice
  password: <%= begin IO.read("#{ENV['HOME']}/.alice_db_pwd").chomp rescue "" end %>\