require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe JournalEntriesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # JournalEntry. As you add validations to JournalEntry, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JournalEntriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all journal_entries as @journal_entries" do
      journal_entry = JournalEntry.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:journal_entries)).to eq([journal_entry])
    end
  end

  describe "GET #show" do
    it "assigns the requested journal_entry as @journal_entry" do
      journal_entry = JournalEntry.create! valid_attributes
      get :show, {:id => journal_entry.to_param}, valid_session
      expect(assigns(:journal_entry)).to eq(journal_entry)
    end
  end

  describe "GET #new" do
    it "assigns a new journal_entry as @journal_entry" do
      get :new, {}, valid_session
      expect(assigns(:journal_entry)).to be_a_new(JournalEntry)
    end
  end

  describe "GET #edit" do
    it "assigns the requested journal_entry as @journal_entry" do
      journal_entry = JournalEntry.create! valid_attributes
      get :edit, {:id => journal_entry.to_param}, valid_session
      expect(assigns(:journal_entry)).to eq(journal_entry)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new JournalEntry" do
        expect {
          post :create, {:journal_entry => valid_attributes}, valid_session
        }.to change(JournalEntry, :count).by(1)
      end

      it "assigns a newly created journal_entry as @journal_entry" do
        post :create, {:journal_entry => valid_attributes}, valid_session
        expect(assigns(:journal_entry)).to be_a(JournalEntry)
        expect(assigns(:journal_entry)).to be_persisted
      end

      it "redirects to the created journal_entry" do
        post :create, {:journal_entry => valid_attributes}, valid_session
        expect(response).to redirect_to(JournalEntry.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved journal_entry as @journal_entry" do
        post :create, {:journal_entry => invalid_attributes}, valid_session
        expect(assigns(:journal_entry)).to be_a_new(JournalEntry)
      end

      it "re-renders the 'new' template" do
        post :create, {:journal_entry => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested journal_entry" do
        journal_entry = JournalEntry.create! valid_attributes
        put :update, {:id => journal_entry.to_param, :journal_entry => new_attributes}, valid_session
        journal_entry.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested journal_entry as @journal_entry" do
        journal_entry = JournalEntry.create! valid_attributes
        put :update, {:id => journal_entry.to_param, :journal_entry => valid_attributes}, valid_session
        expect(assigns(:journal_entry)).to eq(journal_entry)
      end

      it "redirects to the journal_entry" do
        journal_entry = JournalEntry.create! valid_attributes
        put :update, {:id => journal_entry.to_param, :journal_entry => valid_attributes}, valid_session
        expect(response).to redirect_to(journal_entry)
      end
    end

    context "with invalid params" do
      it "assigns the journal_entry as @journal_entry" do
        journal_entry = JournalEntry.create! valid_attributes
        put :update, {:id => journal_entry.to_param, :journal_entry => invalid_attributes}, valid_session
        expect(assigns(:journal_entry)).to eq(journal_entry)
      end

      it "re-renders the 'edit' template" do
        journal_entry = JournalEntry.create! valid_attributes
        put :update, {:id => journal_entry.to_param, :journal_entry => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested journal_entry" do
      journal_entry = JournalEntry.create! valid_attributes
      expect {
        delete :destroy, {:id => journal_entry.to_param}, valid_session
      }.to change(JournalEntry, :count).by(-1)
    end

    it "redirects to the journal_entries list" do
      journal_entry = JournalEntry.create! valid_attributes
      delete :destroy, {:id => journal_entry.to_param}, valid_session
      expect(response).to redirect_to(journal_entries_url)
    end
  end

end
