require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PositionTransfersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # PositionTransfer. As you add validations to PositionTransfer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PositionTransfersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all position_transfers as @position_transfers" do
      position_transfer = PositionTransfer.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:position_transfers)).to eq([position_transfer])
    end
  end

  describe "GET #show" do
    it "assigns the requested position_transfer as @position_transfer" do
      position_transfer = PositionTransfer.create! valid_attributes
      get :show, {:id => position_transfer.to_param}, valid_session
      expect(assigns(:position_transfer)).to eq(position_transfer)
    end
  end

  describe "GET #new" do
    it "assigns a new position_transfer as @position_transfer" do
      get :new, {}, valid_session
      expect(assigns(:position_transfer)).to be_a_new(PositionTransfer)
    end
  end

  describe "GET #edit" do
    it "assigns the requested position_transfer as @position_transfer" do
      position_transfer = PositionTransfer.create! valid_attributes
      get :edit, {:id => position_transfer.to_param}, valid_session
      expect(assigns(:position_transfer)).to eq(position_transfer)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new PositionTransfer" do
        expect {
          post :create, {:position_transfer => valid_attributes}, valid_session
        }.to change(PositionTransfer, :count).by(1)
      end

      it "assigns a newly created position_transfer as @position_transfer" do
        post :create, {:position_transfer => valid_attributes}, valid_session
        expect(assigns(:position_transfer)).to be_a(PositionTransfer)
        expect(assigns(:position_transfer)).to be_persisted
      end

      it "redirects to the created position_transfer" do
        post :create, {:position_transfer => valid_attributes}, valid_session
        expect(response).to redirect_to(PositionTransfer.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved position_transfer as @position_transfer" do
        post :create, {:position_transfer => invalid_attributes}, valid_session
        expect(assigns(:position_transfer)).to be_a_new(PositionTransfer)
      end

      it "re-renders the 'new' template" do
        post :create, {:position_transfer => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested position_transfer" do
        position_transfer = PositionTransfer.create! valid_attributes
        put :update, {:id => position_transfer.to_param, :position_transfer => new_attributes}, valid_session
        position_transfer.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested position_transfer as @position_transfer" do
        position_transfer = PositionTransfer.create! valid_attributes
        put :update, {:id => position_transfer.to_param, :position_transfer => valid_attributes}, valid_session
        expect(assigns(:position_transfer)).to eq(position_transfer)
      end

      it "redirects to the position_transfer" do
        position_transfer = PositionTransfer.create! valid_attributes
        put :update, {:id => position_transfer.to_param, :position_transfer => valid_attributes}, valid_session
        expect(response).to redirect_to(position_transfer)
      end
    end

    context "with invalid params" do
      it "assigns the position_transfer as @position_transfer" do
        position_transfer = PositionTransfer.create! valid_attributes
        put :update, {:id => position_transfer.to_param, :position_transfer => invalid_attributes}, valid_session
        expect(assigns(:position_transfer)).to eq(position_transfer)
      end

      it "re-renders the 'edit' template" do
        position_transfer = PositionTransfer.create! valid_attributes
        put :update, {:id => position_transfer.to_param, :position_transfer => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested position_transfer" do
      position_transfer = PositionTransfer.create! valid_attributes
      expect {
        delete :destroy, {:id => position_transfer.to_param}, valid_session
      }.to change(PositionTransfer, :count).by(-1)
    end

    it "redirects to the position_transfers list" do
      position_transfer = PositionTransfer.create! valid_attributes
      delete :destroy, {:id => position_transfer.to_param}, valid_session
      expect(response).to redirect_to(position_transfers_url)
    end
  end

end
