require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe StatementChargesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # StatementCharge. As you add validations to StatementCharge, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StatementChargesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all statement_charges as @statement_charges" do
      statement_charge = StatementCharge.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:statement_charges)).to eq([statement_charge])
    end
  end

  describe "GET #show" do
    it "assigns the requested statement_charge as @statement_charge" do
      statement_charge = StatementCharge.create! valid_attributes
      get :show, {:id => statement_charge.to_param}, valid_session
      expect(assigns(:statement_charge)).to eq(statement_charge)
    end
  end

  describe "GET #new" do
    it "assigns a new statement_charge as @statement_charge" do
      get :new, {}, valid_session
      expect(assigns(:statement_charge)).to be_a_new(StatementCharge)
    end
  end

  describe "GET #edit" do
    it "assigns the requested statement_charge as @statement_charge" do
      statement_charge = StatementCharge.create! valid_attributes
      get :edit, {:id => statement_charge.to_param}, valid_session
      expect(assigns(:statement_charge)).to eq(statement_charge)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new StatementCharge" do
        expect {
          post :create, {:statement_charge => valid_attributes}, valid_session
        }.to change(StatementCharge, :count).by(1)
      end

      it "assigns a newly created statement_charge as @statement_charge" do
        post :create, {:statement_charge => valid_attributes}, valid_session
        expect(assigns(:statement_charge)).to be_a(StatementCharge)
        expect(assigns(:statement_charge)).to be_persisted
      end

      it "redirects to the created statement_charge" do
        post :create, {:statement_charge => valid_attributes}, valid_session
        expect(response).to redirect_to(StatementCharge.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved statement_charge as @statement_charge" do
        post :create, {:statement_charge => invalid_attributes}, valid_session
        expect(assigns(:statement_charge)).to be_a_new(StatementCharge)
      end

      it "re-renders the 'new' template" do
        post :create, {:statement_charge => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested statement_charge" do
        statement_charge = StatementCharge.create! valid_attributes
        put :update, {:id => statement_charge.to_param, :statement_charge => new_attributes}, valid_session
        statement_charge.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested statement_charge as @statement_charge" do
        statement_charge = StatementCharge.create! valid_attributes
        put :update, {:id => statement_charge.to_param, :statement_charge => valid_attributes}, valid_session
        expect(assigns(:statement_charge)).to eq(statement_charge)
      end

      it "redirects to the statement_charge" do
        statement_charge = StatementCharge.create! valid_attributes
        put :update, {:id => statement_charge.to_param, :statement_charge => valid_attributes}, valid_session
        expect(response).to redirect_to(statement_charge)
      end
    end

    context "with invalid params" do
      it "assigns the statement_charge as @statement_charge" do
        statement_charge = StatementCharge.create! valid_attributes
        put :update, {:id => statement_charge.to_param, :statement_charge => invalid_attributes}, valid_session
        expect(assigns(:statement_charge)).to eq(statement_charge)
      end

      it "re-renders the 'edit' template" do
        statement_charge = StatementCharge.create! valid_attributes
        put :update, {:id => statement_charge.to_param, :statement_charge => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested statement_charge" do
      statement_charge = StatementCharge.create! valid_attributes
      expect {
        delete :destroy, {:id => statement_charge.to_param}, valid_session
      }.to change(StatementCharge, :count).by(-1)
    end

    it "redirects to the statement_charges list" do
      statement_charge = StatementCharge.create! valid_attributes
      delete :destroy, {:id => statement_charge.to_param}, valid_session
      expect(response).to redirect_to(statement_charges_url)
    end
  end

end
