require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe StatementDealLegFillsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # StatementDealLegFill. As you add validations to StatementDealLegFill, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StatementDealLegFillsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all statement_deal_leg_fills as @statement_deal_leg_fills" do
      statement_deal_leg_fill = StatementDealLegFill.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:statement_deal_leg_fills)).to eq([statement_deal_leg_fill])
    end
  end

  describe "GET #show" do
    it "assigns the requested statement_deal_leg_fill as @statement_deal_leg_fill" do
      statement_deal_leg_fill = StatementDealLegFill.create! valid_attributes
      get :show, {:id => statement_deal_leg_fill.to_param}, valid_session
      expect(assigns(:statement_deal_leg_fill)).to eq(statement_deal_leg_fill)
    end
  end

  describe "GET #new" do
    it "assigns a new statement_deal_leg_fill as @statement_deal_leg_fill" do
      get :new, {}, valid_session
      expect(assigns(:statement_deal_leg_fill)).to be_a_new(StatementDealLegFill)
    end
  end

  describe "GET #edit" do
    it "assigns the requested statement_deal_leg_fill as @statement_deal_leg_fill" do
      statement_deal_leg_fill = StatementDealLegFill.create! valid_attributes
      get :edit, {:id => statement_deal_leg_fill.to_param}, valid_session
      expect(assigns(:statement_deal_leg_fill)).to eq(statement_deal_leg_fill)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new StatementDealLegFill" do
        expect {
          post :create, {:statement_deal_leg_fill => valid_attributes}, valid_session
        }.to change(StatementDealLegFill, :count).by(1)
      end

      it "assigns a newly created statement_deal_leg_fill as @statement_deal_leg_fill" do
        post :create, {:statement_deal_leg_fill => valid_attributes}, valid_session
        expect(assigns(:statement_deal_leg_fill)).to be_a(StatementDealLegFill)
        expect(assigns(:statement_deal_leg_fill)).to be_persisted
      end

      it "redirects to the created statement_deal_leg_fill" do
        post :create, {:statement_deal_leg_fill => valid_attributes}, valid_session
        expect(response).to redirect_to(StatementDealLegFill.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved statement_deal_leg_fill as @statement_deal_leg_fill" do
        post :create, {:statement_deal_leg_fill => invalid_attributes}, valid_session
        expect(assigns(:statement_deal_leg_fill)).to be_a_new(StatementDealLegFill)
      end

      it "re-renders the 'new' template" do
        post :create, {:statement_deal_leg_fill => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested statement_deal_leg_fill" do
        statement_deal_leg_fill = StatementDealLegFill.create! valid_attributes
        put :update, {:id => statement_deal_leg_fill.to_param, :statement_deal_leg_fill => new_attributes}, valid_session
        statement_deal_leg_fill.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested statement_deal_leg_fill as @statement_deal_leg_fill" do
        statement_deal_leg_fill = StatementDealLegFill.create! valid_attributes
        put :update, {:id => statement_deal_leg_fill.to_param, :statement_deal_leg_fill => valid_attributes}, valid_session
        expect(assigns(:statement_deal_leg_fill)).to eq(statement_deal_leg_fill)
      end

      it "redirects to the statement_deal_leg_fill" do
        statement_deal_leg_fill = StatementDealLegFill.create! valid_attributes
        put :update, {:id => statement_deal_leg_fill.to_param, :statement_deal_leg_fill => valid_attributes}, valid_session
        expect(response).to redirect_to(statement_deal_leg_fill)
      end
    end

    context "with invalid params" do
      it "assigns the statement_deal_leg_fill as @statement_deal_leg_fill" do
        statement_deal_leg_fill = StatementDealLegFill.create! valid_attributes
        put :update, {:id => statement_deal_leg_fill.to_param, :statement_deal_leg_fill => invalid_attributes}, valid_session
        expect(assigns(:statement_deal_leg_fill)).to eq(statement_deal_leg_fill)
      end

      it "re-renders the 'edit' template" do
        statement_deal_leg_fill = StatementDealLegFill.create! valid_attributes
        put :update, {:id => statement_deal_leg_fill.to_param, :statement_deal_leg_fill => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested statement_deal_leg_fill" do
      statement_deal_leg_fill = StatementDealLegFill.create! valid_attributes
      expect {
        delete :destroy, {:id => statement_deal_leg_fill.to_param}, valid_session
      }.to change(StatementDealLegFill, :count).by(-1)
    end

    it "redirects to the statement_deal_leg_fills list" do
      statement_deal_leg_fill = StatementDealLegFill.create! valid_attributes
      delete :destroy, {:id => statement_deal_leg_fill.to_param}, valid_session
      expect(response).to redirect_to(statement_deal_leg_fills_url)
    end
  end

end
